RomicFinal/urls.py
from django.contrib import admin
from django.urls import path ,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('romicare/', include('romic_employee.urls') )


]

romic_employee/urls.py
from django.urls import path ,include
from romic_employee import views  
from django.contrib.auth import views as auth
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', views.showuserabout ,name='index'), 


    path('login', views.login, name='blog_login'),
    path('logout', views.logout, name='blog_logout'),


    path('activityupload', views.activity_image_view, name='image_upload'),
    path('activity_images', views.display_activity_image, name = 'acitivity_images'),
    path('showactivity',views.showactivity, name = 'show activities'),
    path('editactivity/<int:id>', views.editactivity, name = 'edit acitivity'),  
    path('updateacitivity/<int:id>', views.updateacitivity, name = 'update acitivity'),  
    path('deleteactivity/<int:id>', views.destroyactivity, name = 'delete activity'),



    path('causeupload', views.cause_image_view, name='image_upload'),
    path('cause_images', views.display_cause_image, name = 'cause_images'),
    path('showcause',views.showcause, name = 'show causes'),
    path('editcause/<int:id>', views.editcause, name = 'edit cause'),  
    path('updatecause/<int:id>', views.updatecause, name = 'update cause'),  
    path('deletecause/<int:id>', views.destroycause, name = 'delete cause'),


    path('serviceupload', views.service_image_view, name='service_upload'),
    path('service_images', views.display_service_image, name = 'service_images'),
    path('showservice',views.showservice, name = 'show services'),
    path('editservice/<int:id>', views.editservice, name = 'edit service'),  
    path('updateservice/<int:id>', views.updateservice, name = 'update service'),  
    path('deleteservice/<int:id>', views.destroyservice, name = 'delete service'),

    path('emp', views.emp),  
    path('show',views.show, name = 'show employee'),  
    path('employeeimages', views.display_employee_image, name = 'display_employee'),
    path('edit/<int:id>', views.edit, name = 'edit employee'),  
    path('update/<int:id>', views.update, name = 'update employee'),  
    path('delete/<int:id>', views.destroy, name = 'delete employee'),


    path('blog', views.blog),  
    path('showblog',views.showblog, name = 'show blog'), 
    path('displayblog', views.displayblog, name = 'display_blogs'), 
    path('editblog/<int:id>', views.editblog, name = 'edit blog'),  
    path('updateblog/<int:id>', views.updateblog, name = 'update blog'),  
    path('deleteblog/<int:id>', views.destroyblog, name = 'delete blog'), 

    path('partner', views.partner_image_view),  
    path('showpartner',views.showpartner, name = 'show partner'), 
    path('displaypartner', views.display_partner_image, name = 'display_partners'), 
    path('editpartner/<int:id>', views.editpartner, name = 'edit partner'),  
    path('updatepartner/<int:id>', views.updatepartner, name = 'update partner'),  
    path('deletepartner/<int:id>', views.destroypartner, name = 'delete partner'),


    path('blog', views.blog),  
    path('showblog',views.showblog, name = 'show blog'), 
    path('displayblog', views.displayblog, name = 'display_blogs'), 
    path('editblog/<int:id>', views.editblog, name = 'edit blog'),  
    path('updateblog/<int:id>', views.updateblog, name = 'update blog'),  
    path('deleteblog/<int:id>', views.destroyblog, name = 'delete blog'),



    path('contact', views.contact),  
    path('dashboard',views.showcontact, name = 'dashboard'),  
    path('editcontact/<int:id>', views.editcontact, name = 'edit contact'),  
    path('updatecontact/<int:id>', views.updatecontact, name = 'update contact'),  
    path('deletecontact/<int:id>', views.destroycontact, name = 'delete contact'), 









]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

romic_employee/models.py
from django.db import models
from django.contrib.auth.models import User



class Cause(models.Model):
    causetitle = models.CharField(max_length=50,default = '')
    causedescription = models.TextField(default = '')
    cause_main_img1 = models.ImageField(upload_to='images/',default = '')
    cause_main_img2 = models.ImageField(upload_to='images/',default = '')
    cause_main_img3 = models.ImageField(upload_to='images/',default = '')
    cause_main_img4 = models.ImageField(upload_to='images/',default = '')
    cause_main_img5 = models.ImageField(upload_to='images/',default = '')
    cause_main_img6 = models.ImageField(upload_to='images/',default = '')
    class Meta:  
        db_table = "cause" 


class Service(models.Model):
    servicecategory = models.CharField(max_length=50,default = '', blank=True )
    servicetitle = models.CharField(max_length=50,default = '', blank=True )
    servicedescription1 = models.TextField(default = '',blank=True )
    servicedescription2 = models.TextField(default = '',blank=True )
    servicedescription3 = models.TextField(default = '',blank=True )
    service_main_img = models.ImageField(upload_to='images/', blank=True )
  
    
    class Meta:  
        db_table = "service" 



class Employee(models.Model):    
    ename = models.CharField(max_length=100,default = '')  
    eemail = models.EmailField(default = '')  
    econtact = models.CharField(max_length=15,default = '')
    edescription = models.TextField(default = '')

    class Meta:  
        db_table = "employee" 


class Contact(models.Model):  
    commentname = models.CharField(max_length=100, default = '') 
    commentemail = models.EmailField(default = '') 
    commentsubject = models.TextField(default = '')  
    commentmessage = models.TextField(default = '') 
    class Meta:  
        db_table = "contact" 


class Respond(models.Model):  
    respondmessage = models.TextField(default = '') 
    class Meta:  
        db_table = "response" 


class Donation(models.Model):  
    dname = models.CharField(max_length=100 ,default = '') 
    damount = models.CharField(max_length=100 ,default = '') 
    dtype = models.CharField(max_length=15 ,default = '')
    dcause = models.CharField(max_length=15 ,default = '')  
           
    class Meta:  
        db_table = "donation" 


class Blog(models.Model):  
    btitle = models.CharField(max_length=100,default = '')  
    bauthor = models.CharField(max_length = 100, default='') 
    bdescription = models.TextField(default = '') 
    byoutubelink = models.TextField(default = '') 
       
    class Meta:  
        db_table = "blog" 

        

class About(models.Model):  
    projectname = models.CharField(max_length=100 ,default = '',blank=True) 
    mission = models.TextField(default = '',blank=True)
    vision = models.TextField(default = '',blank=True)
    objective1 = models.TextField(default = '',blank=True)
    objective2 = models.TextField(default = '',blank=True) 
    objective3 = models.TextField(default = '',blank=True) 
    objective4 = models.TextField(default = '',blank=True) 
    objective5 = models.TextField(default = '',blank=True)
    objective6 = models.TextField(default = '',blank=True)
    objective7 = models.TextField(default = '',blank=True) 
    objective8 = models.TextField(default = '',blank=True) 
    objective9 = models.TextField(default = '',blank=True) 
    objective10 = models.TextField(default = '',blank=True)  
    testimonial1 = models.CharField(max_length=100,default = '',blank=True) 
    testimonialrole1 = models.CharField(max_length=100,default = '',blank=True  ) 
    testimonialdecription1 = models.TextField(default = '',blank=True)
    testimonial2 = models.CharField(max_length=100,default = '',blank=True) 
    testimonialrole2 = models.CharField(max_length=100,default = '',blank=True) 
    testimonialdecription2 = models.TextField(default = '',blank=True)
    testimonial3 = models.CharField(max_length=100,default = '',blank=True) 
    testimonialrole3 = models.CharField(max_length=100,default = '',blank=True) 
    testimonialdecription3 = models.TextField(default = '',blank=True)
    testimonial4 = models.CharField(max_length=100,default = '',blank=True) 
    testimonialrole4 = models.CharField(max_length=100,default = '',blank=True) 
    testimonialdecription4 = models.TextField(default = '',blank=True)
    testimonial5 = models.CharField(max_length=100,default = '',blank=True) 
    testimonialrole5 = models.CharField(max_length=100,default = '',blank=True) 
    testimonialdecription5 = models.TextField(default = '',blank=True) 
    location1 = models.CharField(max_length=100,default = '',blank=True) 
    location2 = models.CharField(max_length=100,default = '',blank=True  )
    contact1 = models.CharField(max_length=100,default = '',blank=True) 
    contact2 = models.CharField(max_length=100,default = '',blank=True  )
    Amount1 = models.CharField(max_length=100,default = '',blank=True  )
    Amount2 = models.CharField(max_length=100,default = '',blank=True  )
    Amount3 = models.CharField(max_length=100,default = '',blank=True  )
    Amount4 = models.CharField(max_length=100,default = '',blank=True  )
    Amount5 = models.CharField(max_length=100,default = '',blank=True  )
    Amount6 = models.CharField(max_length=100,default = '',blank=True  )
    status1 = models.CharField(max_length=100,default = '',blank=True  )
    status2 = models.CharField(max_length=100,default = '',blank=True  )
    status3 = models.CharField(max_length=100,default = '',blank=True  )
    status4 = models.CharField(max_length=100,default = '',blank=True  )
    status5 = models.CharField(max_length=100,default = '',blank=True  )
    status6 = models.CharField(max_length=100,default = '',blank=True  )
    genderequity = models.CharField(max_length=100,default = '',blank=True  )
    skills = models.CharField(max_length=100,default = '',blank=True  )
    education = models.CharField(max_length=100,default = '',blank=True  )
    wash = models.CharField(max_length=100,default = '',blank=True  )
    sustainabledevelopment = models.CharField(max_length=100,default = '',blank=True  )
    climatechange = models.CharField(max_length=100,default = '',blank=True  )




    class Meta:  
        db_table = "about" 




class Partner(models.Model):  
    partnername = models.CharField(max_length=100,default = '',blank=True)  
    partnerdescription = models.TextField(default = '',blank=True) 
    partner_main_img = models.ImageField(upload_to='images/' , default = '')   
  
    class Meta:  
        db_table = "partner" 


class Member(models.Model):  
    membername = models.CharField(max_length=100,default = '',blank=True) 
    memberemail = models.EmailField(default = '')  
    memberusername = models.ImageField(upload_to='images/' , default = '')   
  
    class Meta:  
        db_table = "member" 



class Activity(models.Model):
    activitytitle = models.CharField(max_length=50,default = '')
    activitydescription = models.TextField(default = '')
    activity_main_img1 = models.ImageField(upload_to='images/',default = '' )
    activity_main_img2 = models.ImageField(upload_to='images/',default = '') 
    activity_main_img3 = models.ImageField(upload_to='images/',default = '' ) 
    activity_main_img4 = models.ImageField(upload_to='images/', default = '') 
    activity_main_img5 = models.ImageField(upload_to='images/', default = '')  
    activity_main_img6 = models.ImageField(upload_to='images/', default = '')

    class Meta:  
        db_table = "activity" 

romic_employee/forms.py
from django import forms  
from romic_employee.models import Employee  ,About ,Contact ,Blog ,Cause  ,Service ,Activity ,Donation ,Partner ,Member 
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class LoginForm(forms.Form):
    username = forms.CharField(max_length=65)
    password = forms.CharField(max_length=65, widget=forms.PasswordInput)


class MemberForm(forms.ModelForm):
 
    class Meta:
        model = Member
        fields = "__all__" 


class ActivityForm(forms.ModelForm):
 
    class Meta:
        model = Activity
        fields = "__all__" 

 
class CauseForm(forms.ModelForm):
 
    class Meta:
        model = Cause
        fields = "__all__" 

 
class ServiceForm(forms.ModelForm):
 
    class Meta:
        model = Service
        fields = "__all__" 


class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = "__all__"  

    
class BlogForm(forms.ModelForm):  
    class Meta:  
        model = Blog  
        fields = "__all__"  


class CauseForm(forms.ModelForm):  
    class Meta:  
        model = Cause  
        fields = "__all__"  


class AboutForm(forms.ModelForm):  
    class Meta:  
        model = About  
        fields = "__all__" 
        


class ContactForm(forms.ModelForm):  
    class Meta:  
        model = Contact  
        fields = "__all__" 


class DonateForm(forms.ModelForm):  
    class Meta:  
        model = Donation  
        fields = "__all__" 


class PartnerForm(forms.ModelForm):  
    class Meta:  
        model = Partner  
        fields = "__all__" 



class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    phone_no = forms.CharField(max_length = 20)
    first_name = forms.CharField(max_length = 20)
    last_name = forms.CharField(max_length = 20)
    class Meta:
        model = User
        fields = ['username', 'email', 'phone_no', 'password1', 'password2']

romic_employee/templates/blog.html
{% extends 'base.html' %}

{% block content %}

<div class="card-body">

    <div class="form-group col">  
    <label class="row-sm-12 col-form-label row-lg-20"></label>  
    <div class="col-sm-12">  
    <h3><strong>B L O G S     </strong></h3> 
    <p> <strong>Add Blogs </strong></p> 
    </div>  
  </div> 


<form method="POST" class="post-form" action="/blog">  
        {% csrf_token %}  
   

   <div class="row mt-1">
    <label class="col-sm-4 col-form-label"><strong> BLOG TITLE:  </strong></label>  
     <div class="col-sm-12">  
      <div class="card"> 
      {{ form.btitle }} 
      </div> 
    </div>  
  </div> 

   <div class="row mt-1">
    <label class="col-sm-4 col-form-label"><strong> BLOG AUTHOR:  </strong></label>  

    <div class="col-sm-12">  
      <div class="card"> 
      {{ form.bauthor }} 
      </div> 
    </div>  
  </div> 
 
      <div class="row mt-1">
    <label class="col-sm-4 col-form-label"><strong> BLOG DESCRIPTION:  </strong></label>  

    <div class="col-sm-12">  
      <div class="card"> 
      {{ form.bdescription }} 
      </div> 
    </div>  
  </div> 

  
    <div class="row mt-1">
    <label class="col-sm-4 col-form-label"><strong> BLOG YOUTUBE LINK:  </strong></label>  

    <div class="col-sm-12">  
      <div class="card"> 
      {{ form.byoutubelink }} 
      </div> 
    </div>  
  </div>

    
<br/>
<br/>

    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-12">  
    <center><button type="submit" class="btn btn-success">UPLOAD Blog</button></center>  
    </div>  
  </div>  
    </div>  
</form>  



{% endblock %}

romic_employee/templates/editabout.html
{% extends 'base.html' %}

{% block content %}

<div class="card-body">

    <div class="form-group col">  
    <label class="row-sm-12 col-form-label row-lg-20"></label>  
    <div class="col-sm-12">  
    <h3><strong>ROCAF    </strong></h3> 
    <p> <strong>Update Rocaf  </strong></p> 
    </div>  
  </div> 


<form method="POST" class="post-form" action="/updateabout/{{about.id}}">  
        {% csrf_token %}  
 
 

 <div class="container"> 
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> PROJECT NAME:  </strong></label> 
    <div class="col-sm-12">  
         <div class="card">
        <input type="text" name="projectname" id="id-projectname" required maxlength="50" value="{{ about.projectname }}"/>  
    </div>  
  </div>  
</div>
  <br/>

  
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> PROJECT MISSION:  </strong></label> 
    <div class="col-sm-12">  
         <div class="card">
        <input type="text" name="mission" id="id_mission" required maxlength="100" value="{{ about.mission }}" />  
    </div> 
    </div> 
  </div> 

  <br/> 
 
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> PROJECT VISION:  </strong></label> 
    <div class="col-sm-12">  
         <div class="card">
        <input type="text" name="vision" id="id_vision" required maxlength="254" value="{{ about.vision }}" />  
    </div>
    </div>  
  </div>  
    <br/> 
 
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> PROJECT objective:  </strong></label> 
    <div class="col-sm-12">  
         <div class="card">
        <input type="text" name="objective" id="id_objective" required maxlength="15" value="{{ about.objective }}" />  
    </div>
    </div>  
  </div> 


  <br/>
  <br/>

  </div> 

<div class="col-sm-12">  

    <p> <strong>UPDATE ROCAF CONTACTS  </strong></p> 
    </div> 

     <div class="container"> 
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> POSTAL  ADDRESS:  </strong></label> 
    <div class="col-sm-12">  
         <div class="card">
        <input type="text" name="postalddress" id="id-postalddress" required maxlength="50" value="{{ about.postalddress }}"/>  
    </div>
    </div>  
  </div>  
  <br/>

  
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> PHONE NUMBER 1:  </strong></label> 
    <div class="col-sm-12">  
         <div class="card">
        <input type="text" name="phonenumber1" id="id_phonenumber1" required maxlength="100" value="{{ about.phonenumber1 }}" />  
    </div>  
</div>
  </div> 

  <br/> 
 
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> PHONE NUMBER 2:  </strong></label> 
    <div class="col-sm-12">  
         <div class="card">
        <input type="text" name="vision" id="id_phonenumber2" required maxlength="254" value="{{ about.phonenumber2 }}" />  
    </div>  
</div>
  </div>  
    <br/> 
 
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> EMAIL ADDRESS:  </strong></label> 
    <div class="col-sm-12">  
         <div class="card">
        <input type="text" name="aboutemail" id="id_aboutemail" required maxlength="15" value="{{ about.aboutemail }}" />  
    </div>  
</div>

  </div> 

  <br/>
  <br/>


  </div> 


    <div class="col-sm-12">  

    <p> <strong>Update Rocaf Partners  </strong></p> 
    </div> 
     <div class="container"> 
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> PARTNER NAME:  </strong></label> 
    <div class="col-sm-12">
    <div class="card">  
        <input type="text" name="partnername" id="id_partnername" required maxlength="50" value="{{ about.partnername }}"/>  
    </div>
    </div>  
  </div>  
  <br/>

  
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> PARTNER DESCRIPTION :  </strong></label> 
    <div class="col-sm-12">  
        <div class="card">
        <input type="text" name="partnerdescription" id="id_partnerdescription" required maxlength="100" value="{{ about.partnerdescription }}" />  
    </div>  
</div>
  </div> 

  <br/> 
 
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> PARTNER NAME 2:  </strong></label> 
    <div class="col-sm-12">  
        <div class="card">
        <input type="text" name="partnername2" id="id_partnername2" required maxlength="254" value="{{ about.partnername2 }}" />  
    </div>  
</div>
  </div>  
    <br/> 
 
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> PARTNER DECSRIPTION 2:  </strong></label> 
    <div class="col-sm-12">  
        <div class="card">
        <input type="text" name="partnerdescription2" id="id_partnerdescription2" required maxlength="15" value="{{ about.partnerdescription2 }}" />  
    </div>
    </div>  
  </div> 
 </div> 

  <br/>
  <br/>

 <div class="col-sm-12">  

    <p> <strong>Update Rocaf Location  </strong></p> 
    </div> 

     <div class="container"> 
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> LOCATION  MAIN BRANCH:  </strong></label> 
    <div class="col-sm-12">  
        <div class="card">
        <input type="text" name="address1" id="id_address1" required maxlength="50" value="{{ about.address1 }}"/>  
    </div>  
</div>
  </div>  
  <br/>

  
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> LOCATION BRANCH  2:  </strong></label> 
    <div class="col-sm-12">  
        <div class="card">
        <input type="text" name="address2" id="id_address2" required maxlength="100" value="{{ about.address2 }}" />  
    </div>  

  </div> 

  <br/> 
 

 </div> 

  <br/>
  <br/>

<div class="form-group col">  
    <label class="row-sm-12 col-form-label row-lg-20"></label>  
    <div class="col-sm-12">  
    <h3><strong>TESTIMONIALS </strong></h3> 
   
    </div>  
  </div> 
     <div class="container"> 

     <div class="row mt-1">
        <div class="col-sm-12">  
    <p><strong>TESTIMONIAL one   </strong></p> 
   
    </div> 
    <div class="col-sm-12">  
          <div class="card">
        <input type="text" name="testimonial1" id="id_testimonial1" required maxlength="50" value="{{ about.testimonial1 }}"/>  
    </div>  
</div>
  </div>  
  <br/>

    <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> TESTIMONIAL ROLE 1 :  </strong></label> 
    <div class="col-sm-12">  
          <div class="card">
        <input type="text" name="testimonialrole1" id="id_testimonialrole1" required maxlength="50" value="{{ about.testimonialrole1 }}"/>  
    </div>  
  </div>  
</div>
  <br/>

  
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> TESTIMONIAL DESCRIPTION  :  </strong></label> 
    <div class="col-sm-12">  
          <div class="card">
        <input type="text" name="testimonialdecription1" id="id_testimonialdecription1" required maxlength="100" value="{{ about.testimonialdecription1 }}" />  
    </div>  
</div>
  </div>   
  <br/> 



 

 </div> 




  <br/>
  <div class="row mt-1">
        <div class="col-sm-12">  
    <p><strong>TESTIMONIAL 2   </strong></p> 
   
    </div> 

     <div class="container"> 

     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> TESTIMONIAL Second:  </strong></label> 
    <div class="col-sm-12">  
          <div class="card">
        <input type="text" name="testimonial2" id="id_testimonial2" required maxlength="50" value="{{ about.testimonial2 }}"/>  
    </div>  
</div>
  </div>  
  <br/>

    <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> TESTIMONIAL ROLE 2 :  </strong></label> 
    <div class="col-sm-12">  
          <div class="card">
        <input type="text" name="testimonialrole2" id="id_testimonialrole2" required maxlength="50" value="{{ about.testimonialrole2 }}"/>  
    </div>  
      <div class="card">
  </div>  
  <br/>

  
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> TESTIMONIAL DESCRIPTION 2  :  </strong></label> 
    <div class="col-sm-12">  
          <div class="card">
        <input type="text" name="testimonialdecription2" id="id_testimonialdecription2" required maxlength="100" value="{{ about.testimonialdecription2 }}" />  
    </div>  
  </div>   
</div>

  <br/> 


        <div class="row mt-1">
        <div class="col-sm-12">  
    <p><strong>TESTIMONIAL 3  </strong></p> 
   
    </div> 
     <div class="container"> 

     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> TESTIMONIAL Third:  </strong></label> 
    <div class="col-sm-12">  
          <div class="card">
        <input type="text" name="testimonial3" id="id_testimonial3" required maxlength="50" value="{{ about.testimonial3 }}"/>  
    </div>  
</div>
  </div>  
  <br/>

    <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> TESTIMONIAL ROLE 3 :  </strong></label> 
    <div class="col-sm-12">  
          <div class="card">
        <input type="text" name="testimonialrole3" id="id_testimonialrole3" required maxlength="50" value="{{ about.testimonialrole3 }}"/>  
    </div>  
</div>
  </div>  
  <br/>

  
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> TESTIMONIAL DESCRIPTION 3  :  </strong></label> 
    <div class="col-sm-12">  
          <div class="card">
        <input type="text" name="testimonialdecription3" id="id_testimonialdecription3" required maxlength="100" value="{{ about.testimonialdecription3 }}" />  
    </div>  
</div>
  </div>   

  <br/> 


  <div class="row mt-1">
        <div class="col-sm-12">  
    <p><strong>TESTIMONIAL 4  </strong></p> 
   
    </div> 

     <div class="container"> 

     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> TESTIMONIAL Fourth:  </strong></label> 
    <div class="col-sm-12">  
          <div class="card">
        <input type="text" name="testimonial4" id="id_testimonial4" required maxlength="50" value="{{ about.testimonial4 }}"/>  
    </div>  
  </div>  
</div>
  <br/>

    <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> TESTIMONIAL ROLE 4 :  </strong></label> 
    <div class="col-sm-12">  
          <div class="card">
        <input type="text" name="testimonialrole4" id="id_testimonialrole4" required maxlength="50" value="{{ about.testimonialrole4 }}"/>  
    </div>  
</div>
  </div>  
  <br/>

  
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> TESTIMONIAL DESCRIPTION 4  :  </strong></label> 
    <div class="col-sm-12">  
          <div class="card">
        <input type="text" name="testimonialdecription4" id="id_testimonialdecription4" required maxlength="100" value="{{ about.testimonialdecription4 }}" />  
    </div>  
  </div>   
</div>
  <br/> 


       <div class="row mt-1">
        <div class="col-sm-12">  
    <p><strong>TESTIMONIAL 5   </strong></p> 
   
    </div> 

     <div class="container"> 

     <div class="row mt-1">
    <label class="col-sm-4 col-form-label"><strong> TESTIMONIAL Fifth:  </strong></label> 
    <div class="col-sm-12">  
          <div class="card">
        <input type="text" name="testimonial5" id="id_testimonial5" required maxlength="50" value="{{ about.testimonial5 }}"/>  
    </div>  
  </div>  
</div>
  <br/>

    <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> TESTIMONIAL ROLE 5 :  </strong></label> 
    <div class="col-sm-12">  
          <div class="card">
        <input type="text" name="testimonialrole5" id="id_testimonialrole5" required maxlength="50" value="{{ about.testimonialrole5 }}"/>  
    </div>  
  </div>  
</div>

  <br/>

  
     <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> TESTIMONIAL DESCRIPTION 5 :  </strong></label> 
    <div class="col-sm-12">  
          <div class="card">

        <input type="text" name="testimonialdecription5" id="id_testimonialdecription5" required maxlength="100" value="{{ about.testimonialdecription5 }}" />  
    </div>  
  </div>   

 </div>
  <br/>

 

 
 


    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">UPDATE  ABOUT ROCAF </button>  
    </div>  
  </div>  
    </div>  
</form>  

{% endblock %}